// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWJBRb72V4A66ndvMcD3DEmkG4Y7wuJBQ',
    appId: '1:863487705455:web:b4829be643874f1aeb289a',
    messagingSenderId: '863487705455',
    projectId: 'medicaredapp',
    authDomain: 'medicaredapp.firebaseapp.com',
    storageBucket: 'medicaredapp.firebasestorage.app',
    measurementId: 'G-CGFF3KVDYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEM_b-HwemI6HfGuJ1yrSj-v36NOF8SYo',
    appId: '1:863487705455:android:882b318efbcd6b56eb289a',
    messagingSenderId: '863487705455',
    projectId: 'medicaredapp',
    storageBucket: 'medicaredapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-JuaOqL6H2fiwlJWf-tv0LVGtEa1HvkY',
    appId: '1:863487705455:ios:62a35cfcb7013129eb289a',
    messagingSenderId: '863487705455',
    projectId: 'medicaredapp',
    storageBucket: 'medicaredapp.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWJBRb72V4A66ndvMcD3DEmkG4Y7wuJBQ',
    appId: '1:863487705455:web:7ae4a020d0aa0d9beb289a',
    messagingSenderId: '863487705455',
    projectId: 'medicaredapp',
    authDomain: 'medicaredapp.firebaseapp.com',
    storageBucket: 'medicaredapp.firebasestorage.app',
    measurementId: 'G-JZVNM5D55N',
  );
}
